CREATE TABLE IF NOT EXISTS public.appartment_info (
    appartment_id bigint NOT NULL,
    name text,
    description text,
    location text,
    type text,
    is_furnished boolean,
    surface double precision,
    number_of_rooms smallint,
    number_of_bed_rooms smallint,
    energy_class text,
    ges text,
    additional_data text,
    heating_type text,
    heating_mode text,
    floor smallint,
    elevator boolean,
    available_from character varying,
    monthly_charges double precision,
    security_deposite double precision,
    include_charges boolean,
    parking_spaces smallint
);

ALTER TABLE public.appartment_info ALTER COLUMN appartment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appartment_info_appartment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS public.appartments (
    id bigint NOT NULL,
    owner_id uuid NOT NULL,,
    platform_id character varying
);

ALTER TABLE public.appartments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appartments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.appartment_info
    ADD CONSTRAINT appartment_info_appartment_id_key UNIQUE (appartment_id);

ALTER TABLE ONLY public.appartment_info
    ADD CONSTRAINT appartment_info_pkey PRIMARY KEY (appartment_id);

ALTER TABLE ONLY public.appartments
    ADD CONSTRAINT appartments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.appartment_info
    ADD CONSTRAINT appartment_info_appartment_id_fkey FOREIGN KEY (appartment_id) REFERENCES public.appartments(id) ON DELETE CASCADE;

alter table public.appartment_info disable row level security;
alter table public.appartments disable row level security;
