-- Step 1: Create ENUM type for platform_id
CREATE TYPE public.platform_id AS ENUM (
    'swappart',
    'lbc'
);

-- Step 2: Create apartments table
CREATE TABLE IF NOT EXISTS public.apartments (
    id bigint NOT NULL,
    owner_id uuid NOT NULL,
    platform_id public.platform_id NOT NULL  -- Use ENUM type directly
);

ALTER TABLE public.apartments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apartments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Step 3: Create apartment_info table
CREATE TABLE IF NOT EXISTS public.apartment_info (
    apartment_id bigint NOT NULL,
    name text,
    location text,
    is_furnished boolean,
    surface integer,
    energy_class text,
    available_from date,
    rent integer,
    type text,
    ges text,
    description text,
    number_of_rooms integer,
    number_of_bed_rooms integer,
    floor integer,
    elevator boolean,
    parking_spaces integer
);

ALTER TABLE public.apartment_info ALTER COLUMN apartment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apartment_info_apartment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Step 4: Add constraints and relationships
ALTER TABLE ONLY public.apartment_info
    ADD CONSTRAINT apartment_info_apartment_id_key UNIQUE (apartment_id);

ALTER TABLE ONLY public.apartment_info
    ADD CONSTRAINT apartment_info_pkey PRIMARY KEY (apartment_id);

ALTER TABLE ONLY public.apartments
    ADD CONSTRAINT apartments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.apartment_info
    ADD CONSTRAINT apartment_info_apartment_id_fkey FOREIGN KEY (apartment_id)
    REFERENCES public.apartments(id) ON DELETE CASCADE;

-- Step 5: Disable row-level security
ALTER TABLE public.apartment_info DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.apartments DISABLE ROW LEVEL SECURITY;
